"""AddPriceSource

Revision ID: 87abf207457e
Revises: 
Create Date: 2025-01-19 10:36:30.959036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87abf207457e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_source', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_source')

    # ### end Alembic commands ###
